name: Deploy to Reposilite

on:
  push:
    tags:
      - 'v*'

jobs:

  publish:
    name: "Publish to maven repo"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish to Reposilite
        env:
          MAVEN_NAME: '${{ secrets.MAVEN_NAME }}'
          MAVEN_TOKEN: '${{ secrets.MAVEN_TOKEN }}'
        run: ./gradlew publishAllPublicationsToReposilite-repositoryRepository
