name: Deploy to Reposilite

on:
  push:
    tags:
      - 'v*'

jobs:

  publish:
    name: "Publish to maven repo"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3.4.0
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Publish to Reposilite
        uses: gradle/gradle-build-action@v2.2.1
        env:
          MAVEN_NAME: '${{ secrets.MAVEN_NAME }}'
          MAVEN_TOKEN: '${{ secrets.MAVEN_TOKEN }}'
        with:
          arguments:  publishAllPublicationsToReposilite-repositoryRepository
